name: flutter_graphql
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.1.0-dev.1
homepage: https://github.com/snowballdigital/graphql-flutter/tree/master

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.13.1
  http_parser: ^4.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.3
  sqflite: ^2.0.0+3
  graphql_parser2: ^2.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'
